Section "InputClass"
	Identifier "touchpad"
	Driver "libinput"
	Option "Tapping" "on"
	Option "ClickMethod" "buttonareas"
  Option "MiddleEmulation" "true"
	Option "NaturalScroling" "true"
	Option "TappingButtonMap" "lmr"
EndSection

