#!/usr/bin/env sh
#
# Startx init script.
#

# shellcheck disable=SC1090
export WM="${1:-dwm}"

[ -f "$XDG_CONFIG_HOME/X11/Xresources" ] && \
    xrdb -merge "$XDG_CONFIG_HOME/X11/Xresources"

case "$WM" in
    dwm)      . "$HOME/.local/scripts/edw" & while true; do dwm 2> /tmp/.dwm.log; done ;;
    i3)       exec dbus-launch i3 ;;
    openbox)  exec dbus-launch openbox ;;
    sowm)     . "$HOME/.local/scripts/ecm" & exec sowm ;;
    spectrwm) exec dbus-launch spectrwm ;;
    *)        exec dbus-launch "$1" ;;
esac
