#!/usr/bin/env sh
#
# ~/.config/bash/aliases
#

# Terminal application aliases
alias htop-term='st -n htopterm -e htop --user $USER'
alias ranger-term='st -n rangerterm -e ranger'
alias rtorrent-term='st -n rtorrenterm -e rtorrent'
alias vim-term='st -n vimterm -e vim'

# LIbreOffice
alias exel='/usr/lib/libreoffice/program/scalc'
alias pres='/usr/lib/libreoffice/program/simpress'
alias word='/usr/lib/libreoffice/program/swriter'

# VPN
alias oc='bkr $HOME/.local/scripts/opc || $HOME/.local/scripts/opc'
alias poc='sudo pkill openconnect 2>/dev/null'

# Other
alias tabbed-surf='tabbed -d -r 2 surf -e "surf" 2>/dev/null'
