#!/usr/bin/env sh
#
# Script to (un)mount usb devices.
#

[ -n "$(pidof dmenu)" ] && exit

gmt() {
    [ -z "$chs" ] && exit 1
    mp="$(find "$1" -maxdepth 2 -type d | dmenu -p "Type in mount point.")"
    [ "$mp" = "" ] && exit 1

    if [ ! -d "$mp" ]; then
        mkdiryn=$(printf '%s\n%s' "No" "yes" \
            | dmenu -p "$mp does not exist. Create it?")
        [ "$mkdiryn" = "yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
    fi
}

mtu() {
    chs="$(printf '%s' "$udr" | dmenu -p "Mount which drive?" \
        | awk '{print $1}')"
    sudo -A mount "$chs" && notify-send "$chs mounted." && exit
    gmt "/mnt /home"
    sudo -A mount "$chs" "$mp" && notify-send "$chs mounted to $mp."
}

utu() {
    [ -z "$drv" ] && exit
    chs=$(printf '%s' "$drv" | dmenu -p "Unmount which drive?" \
        | awk '{print $1}')
    [ -z "$chs" ] && exit
    sudo -A umount "$chs" && notify-send "$chs unmounted."
}

mnt() {
    udr="$(lsblk -rpo "name,type,size,mountpoint" \
        | awk '$2=="part"&&$4==""{printf "%s (%s)\n",$1,$3}')"

    if [ -z "$udr" ]; then
       printf '%s\n' "No USB drive or Android device detected" && exit
    else 
        printf '%s\n' "USB drive(s) detected." && mtu
    fi
}

umn() {
    drv="$(lsblk -nrpo "name,type,size,mountpoint" \
        | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')"

    if [ -z "$drv" ]; then
        printf '%s\n' "No drives to unmount." && exit
    else
        printf '%s\n' "Unmountable USB drive detected." && utu
    fi
}

err() {
    printf '%s\n' "$1"
    exit 1
}

usg() {
    printf '%s\n'         "usage: dmm [argument]"
    printf '\n'
    printf '%s\n'         "Argument:"
    printf '\t%s\t\t%s\n' "mount"      "- mount drive(s)"
    printf '\t%s\t\t%s\n' "umount"     "- umount drive(s)"
    printf '\t%s\t%s\n'   "-h, --help" "- display this"
    exit
}

case "$1" in
    "mount")          mnt ;;
    "umount")         umn ;;
    ""|"-h"|"--help") usg ;;
    *)                err "$@" ;;
esac
