#!/usr/bin/env sh
#
# Script to setup the multi monitor configuration.
#

if [ "$TOP_TYPE" = "laptop" ]; then
    xrandr --output HDMI2 --off \
        --output DP1 --off \
        --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal \
        --output DP2 --mode 1920x1080 --pos 1920x0 --rotate normal \
        --output HDMI1 --primary --mode 1920x1080 --pos 3840x0 --rotate normal
else
    xrandr --output DP-1 --off \
      --output DP-3 --off \
      --output DP-2 --mode 1920x1080 --pos 0x0 --rotate normal \
      --output HDMI-1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal
fi
